# Define the keywords associated with each tag
tag_links = {
    "fall or spring courses or summer" : "https://registrar.indianatech.edu/calendars/schedules/traditional-schedule-of-classes/",
    "faculty or professors or teachers or professor or files" : "https://academics.indianatech.edu/faculty",
    "programs": "https://academics.indianatech.edu/programs/",
    "academic calender" : "https://registrar.indianatech.edu/calendars/",
    "undergraduate or graduate courses" : "https://registrar.indianatech.edu/calendars/schedules/cps-schedule-of-classes/",
    "transcript" : "https://my.indianatech.edu/ICS/Academics/",
    "grade report or grade or grades" : "https://my.indianatech.edu/ICS/Academics/",
    "commencement or Petition-for-Graduation" : "https://commencement.indianatech.edu/",
    "policies" : "https://registrar.indianatech.edu/policies/",
    "student organisations" : "https://studentlife.indianatech.edu/get-involved/student-orgs/",
    "career center" : "https://careercenter.indianatech.edu/",
    "news" : "https://www.indianatech.edu/news/",
    "WIN or warrior information network or request information" : "https://online.indianatech.edu/support/win/",
    "magazine" : "https://magazine.indianatech.edu/",
    "transfer-students" :"https://www.indianatech.edu/admission-aid/",
    "alternative-academic-paths or honors-program or certificate-programs or bridge-courses or bridge-programs " :"https://academics.indianatech.edu/pathways/",
    "wellness-clinic or health" : "https://www.indianatech.edu/wellness-clinic/",
    "admissions": "https://www.indianatech.edu/admissions/",
    "tuition_financial_aid or costs": "https://online.indianatech.edu/about/costs-aid/",
    "schedule a meeting" : "https://online.indianatech.edu/contact/meeting/",
    "campus_life": "https://www.indianatech.edu/student-life/",
    "athletics": "https://indianatechwarriors.com/",
    "about_us": "https://www.indianatech.edu/about/",
    "contact_information": "https://www.indianatech.edu/contact/",
    "library": "https://library.indianatech.edu/",
    "events": "https://www.indianatech.edu/events/",
    "alumni": "https://www.indianatech.edu/alumni/",
    "careers": "https://www.indianatech.edu/careers/",
    "international_students": "https://www.indianatech.edu/admissions/international/",
    "covid_19_information": "https://www.indianatech.edu/covid-19-updates/",
    "online_programs": "https://online.indianatech.edu/",
    "campus_tours": "https://www.indianatech.edu/visit/",
    "courses": "https://catalog.indianatech.edu/content.php?catoid=18&navoid=677",
    "payment": "https://commerce.cashnet.com/cashnetg/static/epayment/indianatechpay/login?isGuestUser=no",
    "cpt or opt or employment or on campus" : "https://international.indianatech.edu/services/resources/employment/",



    'Dr. Anne Gull': 'https://academics.indianatech.edu/faculty-member/dr-anne-gull/',
    'Courtney Shull': 'https://academics.indianatech.edu/faculty-member/courtney-shull/',
    'Dr. Dawn Anderson': 'https://academics.indianatech.edu/faculty-member/dawn-anderson/',
    'Dr. Mark Bauer': 'https://academics.indianatech.edu/faculty-member/mark-bauer/',
    'Dr. Michael Bechill': 'https://academics.indianatech.edu/faculty-member/michael-bechill/',
    'Dr. Suzanne Beyeler': 'https://academics.indianatech.edu/faculty-member/suzanne-beyeler/',
    'Dr. Justin Boyce': 'https://academics.indianatech.edu/faculty-member/justin-boyce/',
    'Dr. Jonathan Brownlee': 'https://academics.indianatech.edu/faculty-member/jonathan-brownlee/',
    'Dr. Wenjia Cai': 'https://academics.indianatech.edu/faculty-member/wenjia-cai/',
    'Christina Clarke': 'https://academics.indianatech.edu/faculty-member/christina-clarke/',
    'Dr. Sharon Drapala': 'https://academics.indianatech.edu/faculty-member/dr-sharon-drapala/',
    'Dr. Gina Kraft': 'https://academics.indianatech.edu/faculty-member/dr-gina-kraft/',
    'Stacie Kreinbrink, MBA, M.Ed., RHIA, CTR': 'https://academics.indianatech.edu/faculty-member/stacie-kreinbrink/',
    'Dominic Lombardo': 'https://academics.indianatech.edu/faculty-member/dominic-lombardo/',
    'Steven Malloris': 'https://academics.indianatech.edu/faculty-member/steven-malloris/',
    'Dr. Susan McGrade': 'https://academics.indianatech.edu/faculty-member/susan-mcgrade/',
    'Dr. Megan Patton': 'https://academics.indianatech.edu/faculty-member/dr-megan-patton/',
    'Tiffany B. Redies, Esq.': 'https://academics.indianatech.edu/faculty-member/tiffany-b-redies/',
    'Dr. Cortney Robbins': 'https://academics.indianatech.edu/faculty-member/cortney-robbins/',
    'Beth Robinson': 'https://academics.indianatech.edu/faculty-member/beth-robinson/',
    'Dr. Carrie Rodesiler': 'https://academics.indianatech.edu/faculty-member/carrie-rodesiler/',
    'Melissa Schweikert': 'https://academics.indianatech.edu/faculty-member/melissa-schweikert/',
    'Amy Shank': 'https://academics.indianatech.edu/faculty-member/amy-shank/',
    'Dr. Terri Shaw': 'https://academics.indianatech.edu/faculty-member/terri-shaw/',
    'Dr. Alexander Sinelnikov': 'https://academics.indianatech.edu/faculty-member/dr-alexander-sinelnikov/',
    'Kelly Williams': 'https://academics.indianatech.edu/faculty-member/kelly-williams/',
    'Dr. Alicia Wireman': 'https://academics.indianatech.edu/faculty-member/alicia-wireman/',
    'Dr. Angie Fincannon': 'https://academics.indianatech.edu/faculty-member/dr-angie-fincannon/',
    'Dr. Joshua Long': 'https://academics.indianatech.edu/faculty-member/josh-long/',
    'Timothy G. Allwein': 'https://academics.indianatech.edu/faculty-member/tim-allwein/',
    'Dr. Erik Bean': 'https://academics.indianatech.edu/faculty-member/erik-bean/',
    'Dr. Kevin Bottomley': 'https://academics.indianatech.edu/faculty-member/dr-kevin-bottomley/',
    'Lisa Brown': 'https://academics.indianatech.edu/faculty-member/lisa-brown/',
    'Eve-Lynn Clarke': 'https://academics.indianatech.edu/faculty-member/eve-lynn-clarke/',
    'Craig Dyer': 'https://academics.indianatech.edu/faculty-member/craig-dyer/',
    'Trent Grable': 'https://academics.indianatech.edu/faculty-member/trent-grable/',
    'Dr. Crystal Karn': 'https://academics.indianatech.edu/faculty-member/crystal-karn/',
    'Dr. Lisa Kindred': 'https://academics.indianatech.edu/faculty-member/lisa-kindred/',
    'Dr. Scott Liebhauser': 'https://academics.indianatech.edu/faculty-member/scott-liebhauser/',
    'Dr. Staci Lugar Brettin': 'https://academics.indianatech.edu/faculty-member/staci-lugar-brettin/',
    'Dr. Heather St. Peters': 'https://academics.indianatech.edu/faculty-member/heather-st-peters/',
    'Patricia Tanner': 'https://academics.indianatech.edu/faculty-member/patricia-tanner/',
    'Dr. Robert Turick': 'https://academics.indianatech.edu/faculty-member/dr-robert-turick/',
    'Dr. Jeffrey L. Walls, SHRM-SCP, SPHR': 'https://academics.indianatech.edu/faculty-member/jeffrey-walls/',
    'Dr. Lucy Yang': 'https://academics.indianatech.edu/faculty-member/lucy-yang/',
    'Dr. Said Abushamleh': 'https://academics.indianatech.edu/faculty-member/said-abushamleh/',
    'Dr. Ahmad Afaneh': 'https://academics.indianatech.edu/faculty-member/dr-ahmad-afaneh/',
    'Dr. Zakariya Al-Hamouz': 'https://academics.indianatech.edu/faculty-member/zakariya-alhamouz/',
    'Dr. Majed Almotairi': 'https://academics.indianatech.edu/faculty-member/dr-majed-almotairi/',
    'Tammy Barker': 'https://academics.indianatech.edu/faculty-member/tammy-barker/',
    'Peggy Canales': 'https://academics.indianatech.edu/faculty-member/peggy-canales/',
    'Dr. Changhao Chenli': 'https://academics.indianatech.edu/faculty-member/changhao-chenli/',
    'Crysta Burke': 'https://academics.indianatech.edu/faculty-member/crysta-burke/',
    'Dr. Steve Dusseau': 'https://academics.indianatech.edu/faculty-member/steve-dusseau/',
    'Jerome Heaven': 'https://academics.indianatech.edu/faculty-member/jerome-heaven/',
    'Dr. Shadi Jawhar': 'https://academics.indianatech.edu/faculty-member/dr-shadi-jawhar/',
    'Brian Lewandowski': 'https://academics.indianatech.edu/faculty-member/brian-lewandowski/',
    'Zhaojun Li': 'https://academics.indianatech.edu/faculty-member/zhaojun-li/',
    'Dr. Stephanos Mavromoustakos': 'https://academics.indianatech.edu/faculty-member/stephanos-mavromoustakos/',
    'Ihab Mohammed': 'https://academics.indianatech.edu/faculty-member/ihab-mohammed/',
    'Dr. Naga Aditya Musunuri': 'https://academics.indianatech.edu/faculty-member/naga-aditya-musunuri/',
    'Dr. Anna Nagle': 'https://academics.indianatech.edu/faculty-member/anna-nagle/',
    'Saeed Onsorynezhad': 'https://academics.indianatech.edu/faculty-member/saeed-onsorynezhad/',
    'Dr. Maximo J. Ortega': 'https://academics.indianatech.edu/faculty-member/maximo-ortega/',
    'Jack Phlipot': 'https://academics.indianatech.edu/faculty-member/jack-phlipot/',
    'Dr. David Rumsey': 'https://academics.indianatech.edu/faculty-member/david-rumsey/',
    'Brad Shank': 'https://academics.indianatech.edu/faculty-member/brad-shank/',
    'Dr. Yun Su (Suky)': 'https://academics.indianatech.edu/faculty-member/yun-su/',
    'Dr. Shadha Tabatabai': 'https://academics.indianatech.edu/faculty-member/shadha-tabatabai/',
    'Dr. Thomas D. Tran': 'https://academics.indianatech.edu/faculty-member/thomas-tran/',

    
}

keywords = {
    "admissions": ["admission requirements", "application process", "how to apply", "enroll", "deadlines", "admissions office"],
    "academics": ["programs", "majors", "minors", "degrees", "courses", "curriculum", "academic calendar", "departments"],
    "tuition_financial_aid": ["tuition", "fees", "scholarships", "financial aid", "payment plans", "costs", "student loans"],
    "campus_life": ["campus housing", "student life", "residence halls", "dining services", "student activities", "clubs", "organizations"],
    "athletics": ["sports", "teams", "athletics", "games", "schedules", "intercollegiate sports", "intramural", "fitness center"],
    "about_us": ["history", "mission", "values", "leadership", "board of trustees", "president", "accreditation"],
    "contact_information": ["contact", "phone number", "email", "office hours", "directory", "address"],
    "library": ["library", "research resources", "study rooms", "book a room", "digital library", "databases", "academic journals"],
    "events": ["upcoming events", "calendar", "workshops", "seminars", "conferences", "open house", "graduation", "commencement"],
    "alumni": ["alumni", "giving", "donations", "alumni association", "benefits", "events", "stay connected"],
    "careers": ["job openings", "careers", "employment", "internships", "work-study", "career services"],
    "international_students": ["international admissions", "visas", "international programs", "study abroad", "cultural exchange"],
    "covid_19_information": ["covid-19", "pandemic response", "safety guidelines", "health protocols", "vaccination policy"],
    "online_programs": ["online degrees", "distance learning", "e-learning", "online classes", "virtual programs"],
    "campus_tours": ["campus tours", "visit us", "campus visit", "virtual tour", "schedule a visit"]
}

